spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_database_name
    username: my_user
    password: not2tellu
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update